gui:
  showRandomTip: false
  # showIcons: false #breaks in VSCode terminal :-(
git:
  parseEmoji: true
os:
  editPreset: 'vscode'
  #editCommand: 'code -rg {{filename}}'
  #editCommandTemplate: '{{editor}} --goto -- {{filename}}:{{line}}'
customCommands:
  - key: '<c-n>'
    description: 'Show next Git tag version'
    context: 'global'
    command: 'git mkver next'
    subprocess: true
    showOutput: true
  - key: '<c-t>'
    description: 'Tag next version'
    context: 'global'
    command: 'git mkver tag'
    subprocess: true
    showOutput: true