set -g default-terminal 'tmux-256color'
set -g window-size latest
set -g aggressive-resize on
set -g allow-rename off
set -g automatic-rename off
set -g set-titles on
set -g set-titles-string 'repo-ops: #{window_name}#{?pane_dead,,#{?#{@repo_ops_command}, | #{@repo_ops_command},#{?#{m/r:^-?(zsh|bash|fish|sh|dash|ksh|pwsh)$,#{pane_current_command}},, | #{pane_current_command}}}}'
set -g mouse on
set -g status-style 'fg=colour223,bg=colour235'
set -g status-interval 1
set -g status-justify absolute-centre
set -g status-left-length 64
set -g status-right-length 32
set -g status-left '#[fg=colour223,bg=colour239,bold] Layout: #{s/^repo-ops-//:session_name} #[default] '
set -g status-right '#[fg=colour248,bg=colour239] %H:%M  %d-%b-%y #[default]'
set -g window-status-separator ' '
set -g window-status-format ' #I:#W#{?pane_dead,,#{?#{@repo_ops_command}, | #{@repo_ops_command},#{?#{m/r:^-?(zsh|bash|fish|sh|dash|ksh|pwsh)$,#{pane_current_command}},, | #{pane_current_command}}}} '
set -g window-status-current-format ' #I:#W#{?window_zoomed_flag,*,}#{?pane_dead,,#{?#{@repo_ops_command}, | #{@repo_ops_command},#{?#{m/r:^-?(zsh|bash|fish|sh|dash|ksh|pwsh)$,#{pane_current_command}},, | #{pane_current_command}}}} '
set -g window-status-current-style 'fg=colour235,bg=colour214,bold'
set -g window-status-style 'fg=colour223,bg=colour237'
set -g pane-border-style 'fg=colour239'
set -g pane-active-border-style 'fg=colour106'
set -g message-style 'fg=colour223,bg=colour239,bold,fill=colour239'
set -g message-command-style 'fg=colour223,bg=colour239,bold,fill=colour239'
set -g mode-style 'fg=colour235,bg=colour214'
set -g remain-on-exit on
bind-key -T prefix G run-shell 'repo-ops focus #{pane_id}'
bind-key -T prefix -N 'Kill current repo-ops session (confirm)' K confirm-before -p 'Kill session #{session_name} and all its panes? (y/n)' 'kill-session -t "#{session_id}"'
bind-key -T prefix -N 'Restart current pane command (confirm)' R confirm-before -p 'Kill process and restart pane #{pane_id}? (y/n)' 'set-option -pqu -t "#{pane_id}" @repo_ops_command ; respawn-pane -k -t "#{pane_id}"'
