gui:
  showRandomTip: false
  nerdFontsVersion: '3'
  showFileTree: true
git:
  parseEmoji: true
os:
  editPreset: 'vscode'
  #editCommand: 'code -rg {{filename}}'
  #editCommandTemplate: '{{editor}} --goto -- {{filename}}:{{line}}'
promptToReturnFromSubprocess: false
customCommands:
  - key: '<c-n>'
    description: 'Show next Git tag version'
    context: 'global'
    command: 'git mkver next'
    output: terminal
  - key: '<c-t>'
    description: 'Tag next version'
    context: 'global'
    command: 'git mkver tag'
    output: terminal
