import fs from 'node:fs/promises';
import path from 'node:path';
import { digest, portable } from './records.mjs';
import { readJson } from './storage.mjs';

export function relativeSource(root, file, paths = path) {
  const relative = paths.relative(root, file);
  if (!relative || paths.isAbsolute(relative) || relative.split(paths.sep).includes('..')) return undefined;
  if (paths.resolve(root, relative) !== paths.resolve(file)) return undefined;
  const result = relative.split(paths.sep).join('/');
  return portable(result) ? result : undefined;
}

export async function sourceSnapshot({ sourceRoot, sourceFile, loadedBytes }) {
  try {
    if (!Buffer.isBuffer(loadedBytes) || !sourceRoot || !sourceFile) return {};
    const root = await fs.realpath(sourceRoot);
    const file = await fs.realpath(sourceFile);
    const relative = relativeSource(root, file);
    if (!relative || relative !== relativeSource(sourceRoot, sourceFile)) return {};
    if ((await fs.stat(file)).size > 1024 * 1024 || !(await fs.readFile(file)).equals(loadedBytes)) return {};
    let manifest;
    try { manifest = await readJson(path.join(root, '.agentic-tooling', 'generated-manifest.json'), 4 * 1024 * 1024); }
    catch (error) { if (error.code !== 'ENOENT') return {}; }
    const matches = (manifest?.files ?? []).filter(entry => entry.kind === 'agent' && entry.path === relative);
    if (matches.length > 1) return {};
    if (matches.length === 1) {
      const entry = matches[0];
      if (!portable(entry.source) || !/^sha256:[a-f0-9]{64}$/.test(entry.sourceDigest)) return {};
      return { sourceDefinition: entry.source, sourceDigest: entry.sourceDigest };
    }
    if (/Generated by agentic-tooling/.test(loadedBytes.toString('utf8'))) return {};
    return { sourceDefinition: relative, sourceDigest: digest(loadedBytes) };
  } catch { return {}; }
}
